---
- name: Add users to VM
  hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  become: true
  gather_facts: false

  vars_files:
    - ../configs/debian12-add-users.yml

  vars_prompt:
    - name: "target_password"
      prompt: "Enter sudo password for user {{ target_user }} of remote machine at {{ target_host }}"
      private: true

  tasks:
    - name: Set become password
      set_fact:
        ansible_become_password: "{{ target_password }}"

    - name: Create users and configure SSH access
      block:
        - name: Create users and configure SSH access - Create user accounts
          user:
            name: "{{ item.name }}"
            state: present
            createhome: true
            shell: /bin/bash
          loop: "{{ users }}"

        - name: Create users and configure SSH access - Add public keys to authorized_keys
          authorized_key:
            user: "{{ item.name }}"
            state: present
            key: "{{ item.key }}"
          loop: "{{ users }}"

    - name: Grant sudo access to specified users and create default passwords
      block:
        - name: Grant sudo access to specified users and create default passwords - Add sudo users to sudo group
          user:
            name: "{{ item.name }}"
            groups: sudo
            append: true
          when: item.sudoer
          loop: "{{ users }}"

        - name: Grant sudo access to specified users and create default passwords - Set default password for all users
          user:
            name: "{{ item.name }}"
            password: "{{ initial_new_user_password | password_hash('sha512') }}"
          loop: "{{ users }}"

    - name: Add users to docker group
      user:
        name: "{{ item.name }}"
        groups: docker
        append: true
      loop: "{{ users }}"

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Restart Docker to apply group changes
      service:
        name: docker
        state: restarted

    - name: Force users to change password on first login
      command: "chage -d 0 {{ item.name }}"
      loop: "{{ users }}"

    - name: Display message to user
      debug:
        msg: "Users added to VM at {{ target_host }}"